### ISSUE TITLE
Code in Master can not work with Readme (?)

### ISSUE THREAD

**Issue by sylvainbeo** [IGNF/itowns-legacy#12]
The actual code in master can not work with the instructions in the readme.
There's no more index.html ?
(is an error, or am i missing something ?)

**Comment by sylvainbeo** [comment]
Nevermind, it's ok. I did not see the 'git clone -b gh-pages https://github.com/iTowns/itowns.git'.

**Comment by tbroyer** [comment]
Actually, see comments in #10, and #11. I'll take of it all today.
Le 5 févr. 2016 09:09, "Sylvain Beorchia" notifications@github.com a
écrit :

**Comment by vpicavet** [comment]
ok great, let me know when it is ready for #11, last blocker for the release
@sylvainbeo : as the demo on the site will need images from small sample + laser from big, you will probably have to write your own index.html in the site. Or we keep it in gh-pages.

**Comment by sylvainbeo** [comment]
If we move the demo app outside of the itowns repository, the gh-pages is not needed anymore. I thought, the gh-pages was made to get a working demo directly attached to itows's code.

**Comment by tbroyer** [comment]
The `gh-pages` branch will in any case host "releases" of iTowns. Whether it'll continue to also host the demo is another concern.
