### ISSUE TITLE
Update Three.js to r74

### ISSUE THREAD

**Issue by mbredif** [IGNF/itowns-legacy#19]
Currently using R63 in [src/lib/three.js](https://github.com/iTowns/itowns/blob/master/src/lib/three.js)
We could update to a more recent version.

**Comment by mbredif** [comment]
BTW, beware that [src/lib/three.js](https://github.com/iTowns/itowns/blob/master/src/lib/three.js) has been hacked to enable support for 'm3' and 'm3v' uniforms (dbde73ac174d9afe5521079fe57a1903d4a5ba48)

**Comment by mbredif** [comment]
WIP: 08b04309d6796d69134569ef23723eab45612caa
- Projective texturing now works with r73
- lidar and buildings need to be checked (@nosy-b ?)
- navigation is broken (see my changes in the graphicsengine... ) (@nosy-b ?)

**Comment by vpicavet** [comment]
As this is needed for #8 it also looks like a blocker for 1.0.
Any idea of when it will be ready, so that we can release ?

**Comment by nosy-b** [comment]
I'll check. Certainly some migrating from Three r63 to r73 like _"Object3D's position, rotation, quaternion and scale properties are now immutable."_ https://github.com/mrdoob/three.js/wiki/Migration

**Comment by tbroyer** [comment]
IIUC, what #8 (and #20) really needs is an update to r67. While upgrading to r74 (released a couple days ago, unfortunately not yet available in NPM) or r73 would be ideal, maybe we could start with a "baby step" moving to r67 first?

**Comment by vpicavet** [comment]
@tbroyer indeed, first goal is to release v1.0 asap. We can upgrade to latest Three.js versions later on.

**Comment by nosy-b** [comment]
The modification for r74 will work on r73 or even 72.

**Comment by nosy-b** [comment]
Ok for the lidar now. But new ThreeJS seems to force computing bounding box on buffergeometry. As new points comes along it's computationaly heavy.

**Comment by nosy-b** [comment]
Computed once for every series seems cool. Picking ok too.
@mbredif , you may check bati3D before the release :)

**Comment by mbredif** [comment]
it looks like r74 landed on npm : https://www.npmjs.com/package/three

**Comment by vpicavet** [comment]
@mbredif is Bati3D ok ?
Do you want to upgrade to r74 ?

**Comment by mbredif** [comment]
@nosy-b and I are working on it, so that we can upgrade to r74 for the release.

**Comment by mbredif** [comment]
in 410994086664e9dfca0811d3a99c94a297008253 three.js r74 is now pulled from npm (and removed from the sources). I just had to copy the DDSLoader extra since it is not part of the `three` npm package.

@broyer, I have seen a `three-js` npm package which appear to include extensions as well (these extensions are still present in the src/lib directory now). Should we pull from it instead ? I have not succeeded in using it with webpack though.

concerning bati3D, you can see the status when using 
- itowns : 410994086664e9dfca0811d3a99c94a297008253
- datasets : https://github.com/iTowns/itowns-sample-data/tree/Image-MetaData-I2
- setting usingBati3D to true in the index.html.
  The geometry looks ok, but the texturing is wrong. @nosy-b and @qdnguyen, could you look into it ?

**Comment by tbroyer** [comment]
You should be able to import `DDSLoader` as `three/examples/js/loaders/DDSLoader`.
Have a look at the `webpack` branch in iTowns2

**Comment by mbredif** [comment]
#20 merged the update of three.js r74
