### ISSUE TITLE
Measures in demo ?

### ISSUE THREAD

**Issue by vmora** [IGNF/itowns-legacy#2]
Is there a shortcut to enable measurements in the demo ?

**Comment by nosy-b** [comment]
It's available by default when using LaserCloud with the Right Click. Values are in Lambert 93 ( EPSG:2514)

To get distance, you'll need to set LaserCloud.btnSwitchLine to true.

**Comment by vmora** [comment]
It would be nice to have that in the readme since it's a cool feature to demonstrate.

**Comment by vpicavet** [comment]
It is now documented in the default demo.
