### ISSUE TITLE
PB in building to panoramic view switch

### ISSUE THREAD

**Issue by gcebelieu** [IGNF/itowns-legacy#24]
when passing from building view to panoramic view, buildings textures don't disappear (as I imagine they should) . 

See  [movie](http://demos.ign.fr/itowns/demo-itowns.ogv), played with http://itowns.github.io/v1demo.html and a firefox browser.

**Comment by nosy-b** [comment]
In fact it's a normal comportment. If in street level imagery you decide to make the camera goes up it has not effect on the choice of texture for the building, it will keep panoramics. But it would be very easy for the programmer to code a change between 3D building and panoramics on elevation delta.
