### ISSUE TITLE
Demo is broken, due to CORS ?

### ISSUE THREAD

**Issue by mdartic** [IGNF/itowns-legacy#29]
I'm trying your demo on Chrome 50.0.2661.86 (64-bit) on Linux Mint

`XMLHttpRequest cannot load http://itowns.github.io/itowns-sample-data/panoramicsMetaData.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.itowns-project.org' is therefore not allowed access.`

& on Firefox 45.0 on Linux Mint too

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://itowns.github.io/itowns-sample-data/panoramicsMetaData.json. (Reason: CORS header 'Access-Control-Allow-Origin' missing).`

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://itowns.github.io/itowns-sample-data/Buildings3D/EXPORT_1302-13722/export-3DS/ZoneAExporter-1.b3d. (Reason: CORS header 'Access-Control-Allow-Origin' missing).`

Mmm... Could you check that ?

Thanks !

**Comment by nosy-b** [comment]
Yes, was a CORS problem when we created the itowns-project.org pointing to the github page.
It's now corrected.

Thanks!
