### ISSUE TITLE
Documentation on data preparation

### ISSUE THREAD

**Issue by vpicavet** [IGNF/itowns-legacy#3]
It would be great to have documentation on how to generate data for iTowns

**Comment by mbredif** [comment]
Where should we write it? A md file in the master? A wiki page? Somewhere else?

**Comment by vpicavet** [comment]
Let's start with a wiki page on itowns-project and when we will have a documentation framework we will switch to it

**Comment by mbredif** [comment]
Initial draft (images only) is available at https://github.com/iTowns/itowns/wiki . It is written against pull request #20.

**Comment by mbredif** [comment]
https://github.com/iTowns/itowns/wiki is now up to date. While it is not detailing everything, it is now sufficient for a v1 release.
